# Generated by Django 2.1.8 on 2019-07-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0002_remove_rooms_hello'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
    ]
