# Generated by Django 2.1.8 on 2019-07-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='hello',
        ),
    ]
