# Generated by Django 2.1.8 on 2019-07-23 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0003_auto_20190720_0230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
