# Generated by Django 2.1.8 on 2019-07-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='members',
            new_name='memberList',
        ),
    ]
